name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-run-tests:
    name: "Build and Run Tests (${{ matrix.os }}-${{ matrix.arch }})"
    runs-on: [ self-hosted, Linux, "${{ matrix.arch }}" ]
    strategy:
      matrix:
        arch: [ ARM64, X64 ]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Build
        run: go build -v ./...

      - name: Run Tests
        run: go test -v ./...
